import { Fira_Sans_Condensed } from "@next/font/google";
import GlobalState from "../context/page";
import "./globals.css";

const herofont = Fira_Sans_Condensed({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-herofont",
});

export const metadata = {
  title: "felina",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GlobalState>
      <html lang="en">
        <body className={` ${herofont.variable} `}>
          <div className="">{children}</div>
        </body>
      </html>
    </GlobalState>
  );
}
